### ISSUE TITLE
JS Error in Chrome

### ISSUE THREAD

**Issue by wffurr** [martindale/shipviewer#1]
Version 47.0.2526.16 beta (64-bit)

Console:

```
Uncaught SyntaxError: Unexpected token ILLEGAL
http://www.eveonline.com/ccp/js/scripts-130123155501.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
modernizr.custom.js:1 Uncaught SyntaxError: Unexpected token ILLEGAL
52shipviewer.js:1401 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
534shipviewer.js:1401 Uncaught TypeError: Cannot read property 'getElementsByTagName' of nullCCPShipViewer.Tw2EffectRes.Prepare @ shipviewer.js:1401PrepareLoop @ shipviewer.js:420Tw2Device.Tick @ shipviewer.js:842tick @ shipviewer.js:4
```

Stack trace:

```
"TypeError: Cannot read property 'getElementsByTagName' of null at Tw2EffectRes.CCPShipViewer.Tw2EffectRes.Prepare (http://shipviewer.ericmartindale.com/js/shipviewer.js:1401:18)
at Array.PrepareLoop (http://shipviewer.ericmartindale.com/js/shipviewer.js:420:40)
at Tw2Device.Tick (http://shipviewer.ericmartindale.com/js/shipviewer.js:842:78)
at tick (http://shipviewer.ericmartindale.com/js/shipviewer.js:4:36)"
```

**Comment by martindale** [comment]
It looks like CCP changed their resources and the API they expose, so I'll need to dig in further to reverse-engineer their new updates.  This is currently a low-priority item for me, but I'll take a look soon.
